task: obb
mode: train
model: configs/models/lsknet_t_obb.yaml
epochs: 800
batch: 16
imgsz: 1280
workers: 8
device: 4,5,6,7
cache: ram
optimizer: AdamW
lr0: 0.0006
lrf: 0.01
momentum: 0.9
weight_decay: 0.05
warmup_epochs: 5.0
cos_lr: true
close_mosaic: 80
amp: true
patience: 200
save: true
save_period: 50
plot_period: 50
seed: 42
deterministic: true
box: 7.5
cls: 0.75
cls_pw: 0.25
focal_gamma: 1.0
focal_alpha: 0.25
dfl: 1.5
angle: 1.0
mosaic: 0.25
mixup: 0.0
cutmix: 0.0
hsv_h: 0.015
hsv_s: 0.4
hsv_v: 0.3
degrees: 180.0
translate: 0.05
scale: 0.2
fliplr: 0.5
flipud: 0.5
conf: 0.05
iou: 0.7
max_det: 600
